### ISSUE TITLE
Handle PNG images

### ISSUE THREAD

**Issue by MLnick** [IBM/MAX-Facial-Age-Estimator#13]
Currently the API crashes when a PNG is posted. We should either handle that gracefully, or better we should convert internally PNG -> RGB (4 ch -> 3 ch) so that we can handle it. In that case we should add a doc comment and note in the README about how we handle PNGs

**Comment by zuhito** [comment]
I encountered the same problem. `Internal Server Error` occurred when uploading a PNG file. As the README.md explains, I think that it is good to support both PNG and JPG as input data format.

<img width="1280" alt="fae" src="https://user-images.githubusercontent.com/6851138/53294732-d2a29700-382f-11e9-9005-bf55daf0ea28.png">

**Comment by MLnick** [comment]
I think this is best handled at the level of `MAX-Framework` to provide common utility functions that can be re-used by all relevant models. See https://github.com/IBM/MAX-Framework/issues/8
