### ISSUE TITLE
inconsistent link to model assets in COS

### ISSUE THREAD

**Issue by vabarbosa** [IBM/MAX-Facial-Age-Estimator#37]
in the [`Dockerfile`](https://github.com/IBM/MAX-Facial-Age-Estimator/blob/master/Dockerfile#L4) the models assets are downloaded from:

```
ARG model_bucket=http://max-assets.s3.us.cloud-object-storage.appdomain.cloud/facial-age-estimator/1.0
ARG model_file=assets.tar.gz
```

however, in the [`README.md`](https://github.com/IBM/MAX-Facial-Age-Estimator/blob/master/README.md) the **IBM Cloud Object Storage** link points to:

```
http://max-assets.s3.us.cloud-object-storage.appdomain.cloud/facial-age-estimator.tar.gz
```

these should probably be point to the same URL/model asset.

**Comment by I-Hong** [comment]
Thanks @vabarbosa.
