### ISSUE TITLE
Document "face_box"

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-Facial-Age-Estimator#5]
What does `face_box` represent? Is the input image re-sized?

**Comment by MLnick** [comment]
Can we document the meaning of the bounding box format (see e.g. `[x, y, h, w]` or [`y1, x1, .. ]` or whatever)

**Comment by I-Hong** [comment]
Yes, how about `a list of (x1, y1, w, h) that describes the coordinates of the upper left corner and the width and height of the bounding box`?
